#!/usr/bin/env python3.10
from enum import Enum
from common_utilities import RedisHandler

class Action(Enum):
    NO_ACTION = 0
    ACTION_LOCK_SCREEN = 1
    ACTION_SIGN_OUT = 2
    ACTION_WARNING = 3
    ACTION_ERROR = 4


class Reason(Enum):
    EMPTY_REASON = 0
    REASON_PHONE_DETECTION = 1
    REASON_CABLE_REMOVE = 2
    REASON_CAMERA_NOT_ATTACH = 3
    REASON_CONNECT_TO_INTERNET = 4
    REASON_SPOOF_IMAGE = 5
    REASON_WRONG_USER = 6
    REASON_NO_FACE = 7
    REASON_BLOCKED_CLIENT = 8
    REASON_PAUSED_CLIENT = 9
    REASON_RESUME_CLIENT = 10
    REASON_CLIENT_NOT_AVAILABLE = 11
    REASON_RATE_LIMIT_EXCEEDED = 12
